### ISSUE TITLE
Don't format text with %s, use %v

### ISSUE THREAD

**Issue by langston-barrett** [acmacalister/skittles#1]
In the signature of Skittles' methods, `text` is an `interface{}`. However, in the format strings, skittles uses `%s` instead of the more general `%v`. I'm happy to put a PR in, would you accept one?

**Comment by acmacalister** [comment]
I would. That would be good change. I originally had it as `%s` format specific sense `text` use to be a `string`. Then I wanted to print other types (such as errors) and never went back and changed it to `%v`.
